spring:
  jpa:
    show-sql: true

  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: gemini-2.0-flash

    anthropic:
      api-key: ${CLAUDE_API_KEY}

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
    webhook:
      relab-mfb-secret: ${WEBHOOK_HMAC_SECRET}

logging:
  level:
    com.relab.budget: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
